CREATE DATABASE HIBERNATE CHARACTER SET 'utf8';

USE HIBERNATE;

CREATE TABLE UTILISATEUR (
	ID INT AUTO_INCREMENT, 
	NOM VARCHAR(30) NOT NULL,
	PRENOM VARCHAR(30) NOT NULL,
	ADRESSE VARCHAR(75) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	MDP VARCHAR(50) NOT NULL UNIQUE,  
	PRIMARY KEY(ID)
);

CREATE TABLE PRODUIT (
	REFERENCE INT AUTO_INCREMENT, 
	NOM VARCHAR(50) NOT NULL,
	CODEPRODUIT CHAR(12) NOT NULL UNIQUE,
	QUANTITE INT NOT NULL,
	DATEPEREMPTION DATE NOT NULL, 
	PRIMARY KEY(REFERENCE)
);



INSERT INTO UTILISATEUR (NOM, PRENOM, ADRESSE, EMAIL, MDP) VALUES ('Jean', 'LASALLE', '1 rue Eugene Sue', 'jean@toto.fr', 'Jean38');
INSERT INTO UTILISATEUR (NOM, PRENOM, ADRESSE, EMAIL, MDP) VALUES ('Marc', 'LAROUE', '17 rue Victor Hugo', 'marc@toto.fr', 'Marc38');
INSERT INTO UTILISATEUR (NOM, PRENOM, ADRESSE, EMAIL, MDP) VALUES ('Axelle', 'LEBLANC', '4 place de la fourberie', 'axelle.leblanc@toto.fr', 'Axelle38');
INSERT INTO UTILISATEUR (NOM, PRENOM, ADRESSE, EMAIL, MDP) VALUES ('Patricia', 'LEBLANC', '15 rue de la dramaturgie', 'patricia.leblanc@toto.fr', 'Patricia38');
INSERT INTO UTILISATEUR (NOM, PRENOM, ADRESSE, EMAIL, MDP) VALUES ('Eva', 'PETIT', '24 place de la coquinerie', 'eva.petit@toto.fr', 'Eva38');


INSERT INTO PRODUIT (NOM, CODEPRODUIT, QUANTITE, DATEPEREMPTION) VALUES ('Yaourt Bio', '785vgt653', 17, '2021-05-16');
INSERT INTO PRODUIT (NOM, CODEPRODUIT, QUANTITE, DATEPEREMPTION) VALUES ('Pain viennois', '563dre895', 02, '2021-03-17'); 
INSERT INTO PRODUIT (NOM, CODEPRODUIT, QUANTITE, DATEPEREMPTION) VALUES ('Soda citron vert', '752vgt275', 42, '2021-05-25'); 
INSERT INTO PRODUIT (NOM, CODEPRODUIT, QUANTITE, DATEPEREMPTION) VALUES ('Café corsé', '245vgt996', 37, '2021-10-22'); 
INSERT INTO PRODUIT (NOM, CODEPRODUIT, QUANTITE, DATEPEREMPTION) VALUES ('Thé noir', '452vgt246', 10, '2021-11-07');  